### ISSUE TITLE
Pull request #8 caused some build errors

### ISSUE THREAD

**Issue by ajw1970** [mestekmachinery/Machine_Manuals#10]
$ bundle exec liquidoc --config _ops/build-docs.yaml --data _data/products.yml,_data/product-configurations.yml
INFO: File built: /mnt/c/Dev/Machine_Manuals/_build/pre/build-docs.yaml
INFO: Copied assets/images/controls/screens/pro-fabriduct to _build/products/pro-fabriduct/images.
ERROR: Unexpected missing source in migrate action (assets/images/controls/screens/coil-strip-processor to _build/products/coil-strip-processor/images).
Traceback (most recent call last):
        9: from /usr/local/bin/liquidoc:23:in `<main>'
        8: from /usr/local/bin/liquidoc:23:in `load'
        7: from /var/lib/gems/2.7.0/gems/liquidoc-0.12.0.pre.rc4/bin/liquidoc:3:in `<top (required)>'
        6: from /var/lib/gems/2.7.0/gems/liquidoc-0.12.0.pre.rc4/bin/liquidoc:3:in `require'
        5: from /var/lib/gems/2.7.0/gems/liquidoc-0.12.0.pre.rc4/lib/liquidoc.rb:1435:in `<top (required)>'
        4: from /var/lib/gems/2.7.0/gems/liquidoc-0.12.0.pre.rc4/lib/liquidoc.rb:124:in `config_build'
        3: from /var/lib/gems/2.7.0/gems/liquidoc-0.12.0.pre.rc4/lib/liquidoc.rb:129:in `iterate_build'
        2: from /var/lib/gems/2.7.0/gems/liquidoc-0.12.0.pre.rc4/lib/liquidoc.rb:129:in `each'
        1: from /var/lib/gems/2.7.0/gems/liquidoc-0.12.0.pre.rc4/lib/liquidoc.rb:167:in `block in iterate_build'
/var/lib/gems/2.7.0/gems/liquidoc-0.12.0.pre.rc4/lib/liquidoc.rb:951:in `copy_assets': MissingSourceExit (RuntimeError)

**Comment by ajw1970** [comment]
Looks to be caused by naming changes _data/products.yml

![image](https://user-images.githubusercontent.com/3105267/135900443-b8f4c1a2-44f1-46f2-bab4-c112e4014c6f.png)

**Comment by briandominick** [comment]
I thought I warned you about this in my PR? Sorry if I forgot to -- I meant to reconcile before making a final push.

It's usually best to let contrinbutors merge their own PRs. I almost always want to clean something up, but I try not to do too much work before I get a feel for if the thing is going to work. I'll try to tag WIP onto anything that's still in progress.

**Comment by ajw1970** [comment]
> I thought I warned you about this in my PR? Sorry if I forgot to -- I meant to reconcile before making a final push.

I may have missed that. No worries.

> It's usually best to let contrinbutors merge their own PRs. I almost always want to clean something up, but I try not to do too much work before I get a feel for if the thing is going to work. 

Good to know. Thank you. 

> I'll try to tag WIP onto anything that's still in progress.

Sounds good. Thank you.
